import "./globals.css";
import { Ubuntu } from "next/font/google";
import { Navbar, NavigationButtons } from "./components";

const ubuntu = Ubuntu({
  subsets: ["latin"],
  weight: ["300", "400", "500", "700"],
});

export const metadata = {
  number: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${ubuntu.className} min-h-screen flex md:justify-center md:flex-col relative`}
      >
        <div className="flex flex-col md:flex-row md:justify-between max-w-[935px] md:w-[90%] mx-auto rounded-xl md:shadow-2xl w-full">
          <aside className="md:p-4 md:pr-0">
            <Navbar />
          </aside>
          <div className="flex flex-col items-center w-[90%] md:w-full mx-auto translate-y-[-92px] md:translate-y-0 bg-white rounded-lg">
            {children}
          </div>
        </div>
        <div className="md:hidden absolute bottom-4 right-0 left-0">
          <div className="w-[90%] mx-auto">
            <NavigationButtons />
          </div>
        </div>
      </body>
    </html>
  );
}
